fixed cv-hpdcache-verif/issues/2 related to License headers for Perl …
openhwgroup/cv-hpdcache-verif pull request #8
Opened 2024-10-21 12:24 UTC by ludovicpion

Fixed https://github.com/openhwgroup/cv-hpdcache-verif/issues/2

2024-10-22 08:20 UTC, khandelwaltanuj approved these changes

2024-10-22 16:34 UTC, MikeOpenHWGroup requested changes
Thanks @ludovicpion.  Copyright headers look good.  However, each header has the following line at the bottom:
`##  Description : Agent for the hpdcache request`

This is probably a copy and paste error.

2024-10-23 06:53 UTC, ludovicpion commented
Hi @MikeOpenHWGroup ,

Indeed, it is a copy/paste error. It is now fixed.

Thanks

2024-10-23 16:41 UTC, MikeOpenHWGroup approved these changes

2024-10-23 16:41 UTC, merged